### ISSUE TITLE
Clean Up Sidebar UI

### ISSUE THREAD

**Issue by sowmyasub** [NASA-IMPACT/admg-backend#276]
## Context
This issue was repurposed to be part of [EPIC: MI Workflow Redesign #270](https://github.com/NASA-IMPACT/admg-backend/issues/270)

Currently, the sidebar on drafts can be confusing to navigate and be somewhat messy.  How can we improve this experience?

## Current
> ![image](https://user-images.githubusercontent.com/10764915/183661294-2dbcbe22-68ac-425d-a629-814afbba8bef.png)
> https://admgstaging.nasa-impact.net/drafts/edit/a5ca9504-6f2c-4d65-8cf0-f0d5cfb6f31d
- Example of an unpublished draft where the side bar is on the right-side

> ![image](https://user-images.githubusercontent.com/10764915/183661527-0cb85cb0-13bc-4b34-abab-e1136271374f.png)
> https://admgstaging.nasa-impact.net/drafts/edit/092e31e7-1227-47f3-af14-6c80ed178d96
- Example of a published draft with the diff view where the side bar is at the bottom

## New
> ![image](https://user-images.githubusercontent.com/10764915/183663156-fda00125-01f8-4bc9-bb13-796009b99428.png)
> https://www.figma.com/file/zY7BS9fR1huZ0CieHf3Dm8/MI-Workflow-Change?node-id=286%3A25633

> ![image](https://user-images.githubusercontent.com/10764915/183663585-b121bbba-1b47-47fe-a9e3-8bc2b4ea0343.png)
> https://www.figma.com/file/zY7BS9fR1huZ0CieHf3Dm8/MI-Workflow-Change?node-id=286%3A26852

- Collapse information into an accordion
- Only allow one accordion to open at a time (not like the mockup)
- For the `Dependent Drafts`, created 1 indented section for each of:
  - `Deployments`
  - `IOPs`
  - `Significant Events`
  - `CDPIs`
- Only the logo is not collapsed because it's a nice visual representation of the campaign, platform, or instrument 

> ![image](https://user-images.githubusercontent.com/10764915/183664562-4e7e7cd3-48f7-4076-b468-73f3303da27c.png)
> https://www.figma.com/file/zY7BS9fR1huZ0CieHf3Dm8/MI-Workflow-Change?node-id=286%3A25716

- For the diff view, we can keep the current behaviour where the sidebar stacks at the bottom

> ![image](https://user-images.githubusercontent.com/10764915/183665161-beecbb56-11e6-4838-86be-24aff9597388.png)
> https://www.figma.com/file/zY7BS9fR1huZ0CieHf3Dm8/MI-Workflow-Change?node-id=286%3A26004

- For a published view, we can still show the logo and history

**Comment by heidimok** [comment]
Closing this issue as we have released the new MI workflow and do not plan to make these additional changes.
