### ISSUE TITLE
Credentials error when triggered db to prod UI workflow

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-backend#618]
## Context
We had addressed an issue around deploying content from db to prod UI by create the token needed to trigger the CASEI workflow in this issue: https://github.com/NASA-IMPACT/ADMG-project/issues/963

## Issue
When clicking on the deploy website button in the MI, an error message was shown on the top banner:
`Failed to trigger deployment: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}`

![image](https://github.com/NASA-IMPACT/admg-backend/assets/10764915/e2537173-7635-4b5c-8fd0-ea0692b0104b)

## Expected Outcome
By clicking on the deploy website button, it's expected that the CASEI workflow would be triggered and new content published in the MI would appear in the CASEI front end UI.

**Comment by Tammo-Feldmann** [comment]
@heidimok We did not have a valid bearer token for the production MI. I have added one with a comment that we might consider OIDC or rotating bearer tokens if we need long term support for this functionality. For now the functionality is restored until the bearer token expires and I would consider this issue completed.
